name: Publish Docker image to my seyhello/revolgy-task repository
on:
  push:
    branches: [ master ]
    paths:
    - 'service-db/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: seyhello/revolgy-task
          dockerfile: service-db/Dockerfile
          tags: service-db
